### ISSUE TITLE
4.0 crash with "unrecognized selector sent ..."

### ISSUE THREAD

**Issue by dingosky** [marcbaldwin/GestureRecognizerClosures#16] opened 2017-10-13 22:47 UTC
**Steps to reproduce**:
  - Upgrade to 4.0 (for me it was from 3.1.0)
  - Run app that was fine with 3.1.0
  - Tap view with installed tap gesture recognizer
  - **_boom_**

**Error**
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_TtGC25GestureRecognizerClosures14ClosureHandlerCSo22UITapGestureRecognizer_ handle]: unrecognized selector sent to instance 0x600000037200'`

**Comments**
I'm using this library in a demo app that is quite simple. I have two gesture recognizers attached to the same image: one single tap, the other a double tap. The app works fine with version 3.1 but not after upgrade to 4.0. The crash happens immediately on the tap and the underlying block is not called.

I've rolled back to 3.1 to verify correct behavior and upgraded to 4.0 again to validate crashing behavior (with no other changes to app of course).

**Comment by marcbaldwin** [comment] 2017-10-15 08:01
Hey, which version of Swift and Xcode are you using?

**Comment by dingosky** [comment] 2017-10-15 15:48
Xcode 9.0 (9A235) and Swift 4.0 running on macOS 10.13.  I was running 10.12.6 but update yesterday. Just checked and got the same result on 10.13.

Pardon my not having put that info in the bug report.

**Comment by alvinpb** [comment] 2017-10-16 10:23
Also seeing this issue.

**Comment by marcbaldwin** [comment] 2017-10-16 21:37
Hey guys, I've been unable to reproduce your issue. What version of iOS are you running the app on? Also, could you please paste me the code where you add the gestures.

The below worked for me.
```
imageView.onTap { tap in

}

imageView.onDoubleTap { doubleTap in

}
```

**Comment by dingosky** [comment] 2017-10-16 21:57
Confirmed that my app works with 3.1.0 and fails with 4.0 using:
- iPad Pro: iOS 11.0
- iOS Simulator: 10.3.1
- iPad mini: 9.3.5

The code attaching the recognizers is:

`view.onTap { _ in
  ...
}`

`view.onDoubleTap { _ in
  ...
}
`

**Comment by dingosky** [comment] 2017-10-16 22:57
A bit more info:

```
po stopLight.view.gestureRecognizers!
▿ 1 element
  - 0 : <UITapGestureRecognizer: 0x6100001aa100; state = Possible; view = <UIView 0x7faa5410bea0>; target= <(action=handle, target=<_TtGC25GestureRecognizerClosures14ClosureHandlerCSo22UITapGestureRecognizer_ 0x6100002373e0>)>>

```
The above is printed after calling `stopLight.view.onTap` but before `stopLight.view.onDoubleTap`.  It shows the tap gesture recognizer added to the view.

This is the subsequent exception:

```
2017-10-16 15:54:40.518 StopLight[9547:2560314] -[_TtGC25GestureRecognizerClosures14ClosureHandlerCSo22UITapGestureRecognizer_ handle]: unrecognized selector sent to instance 0x6100002373e0
```

So the unrecognized call to `handle` is on the closure setup by `onTap`.

**Comment by marcbaldwin** [comment] 2017-10-17 15:40
I've managed to reproduce the issue 👍 Working on a fix.

**Comment by marcbaldwin** [comment] 2017-10-17 19:12
Hey @dingosky, @alvinpb, I've release a new version `4.0.1` which I hope fixes the issue. Please let me know If it has and I'll close this issue.

**Comment by dingosky** [comment] 2017-10-17 23:47
4.0.1 does indeed fix the issue. Thanks for the quick response.

**Comment by marcbaldwin** [comment] 2017-10-18 06:58
Excellent! Closing.

**Closed by marcbaldwin** 2017-10-18 06:58 UTC
Labels: bug
